### ISSUE TITLE
bp-moderation to work with all  bbpress ??

### ISSUE THREAD

**Issue by g2eat** [francescolaffi/BP-Moderation#10]
im having some issues,
im using wordpress 3.5.2 multisite with a custom theme, o

Theme: Cinematix 

Plugins used: 
buddypress 1.8
bbpress 2.3.2
Orbisius bbPress Enhancer
Contact Form 7
1. flag text shows in bbpress forum but it does not work .
2. when i press flag in forum the processing icon keeps turning then nothing happens

**Comment by francescolaffi** [comment]
are you using the legacy group forums?

**Comment by g2eat** [comment]
im not sure but i am using default buddypress groups and bbpress for forum

**Comment by francescolaffi** [comment]
if you have installed bbpress plugin and the legacy forum are not enabled on buddypress components, then you are not using legacy forum. 
bpmoderation 0.1.x supports only legacy group forums, and the flag links shouldn't show at all in the new bbpress 2.x forums, maybe your theme is using the same filters as the old legacy forums, in that case you can deactivate the forum topic content type from the bp-moderation settings.
there should be some other solution for bbpress moderation, there wont be any integrated in bp-moderation until next major version.
