### ISSUE TITLE
Flags not showing on Activity Stream uploads

### ISSUE THREAD

**Issue by madcap66** [francescolaffi/BP-Moderation#11]
Hi there

Great plugin but I was wondering why the flags don't show on comments and uploads on BP Activity Stream.

I'm using latest rtMedia (Buddypress-media), latest BP and latest Wordpress.

TIA

**Comment by francescolaffi** [comment]
every content type(posts, comments, ...) need some code to integrate with bp-moderation, the plugin includes integration with the core types, but for 3rd party plugins you wont usually find the integration builtin. I dont know/use that plugin so I cant write it, but there is documentation on how to do it in the readme under integration guide  (you can see it here http://wordpress.org/plugins/bp-moderation/other_notes/ )

You can ask rtmedia author to write the integration, or try it yourself. If support is needed for the integration on bp-moderation ask here!

**Comment by madcap66** [comment]
Thanks Francesco...I'll have a look and see what I can work out.
