### ISSUE TITLE
Admin Menu Image on MP6

### ISSUE THREAD

**Issue by mrjarbenne** [francescolaffi/BP-Moderation#13]
MP6 is the test plugin for a future reface of the Dashboard in WordPress http://wordpress.org/plugins/mp6/. With that plugin enabled, the image in the Network Admin Dashboard doesn't look right. This isn't a pressing issue, but it's something you may want to attend to before MP6 becomes the default view: http://www.screencast.com/t/EVOkJn8X

**Comment by francescolaffi** [comment]
tried with mp6 and I just see the gear icon for custom menu without the custom icon...what wp,bp,mp6 versions are you using?
anyway I'm tagging this for the next major release of bp-mod that I trust will be ready before mp6 get merged in wp core

**Comment by mrjarbenne** [comment]
I'm using the latest from the repo

WP 3.6
BP 1.8.1
MP6 1.9

I can try the dev version from github here: I haven't looked into that yet.

**Comment by francescolaffi** [comment]
I'm using the same versions, even with bp-mod 0.1.7 I see the gear icon, also mp6 1.9 has this css that reset all menu images, so there shouldnt be broken icons given that the most of the plugins never tested this admin interface

``` css
/* hide images in admin menu items */
.wp-menu-image img {
    display: none;
}

.wp-menu-image {
    background-image: none !important;
}
```

this css override bp-mod flag icon too, at least in my browser (chrome), maybe the mp6 css doesn't work the same way on your browser, or you're getting a cached mp6 stylesheet without these rules.

**Comment by mrjarbenne** [comment]
Downloaded the new master and all is good.
