### ISSUE TITLE
Activity Comment Reported Links don't ReDirect Correctly

### ISSUE THREAD

**Issue by mrjarbenne** [francescolaffi/BP-Moderation#14]
Status Updates when you examine the link, seem to point at a URL formatted like this: 

http://domain.com/activity/p/163210/ but then end up correctly redirecting to http://domain.com/members/username/activity/163210/

Activity Comments don't redirect in the same way, and end up at a 404. 

Here's a short video illustrating what I'm seeing: http://www.screencast.com/t/0BemnQCVCCNb

**Comment by francescolaffi** [comment]
Thank for the clear report, I'll find a better way to get comments url.

**Comment by francescolaffi** [comment]
fixed on the dev version here on github

**Comment by mrjarbenne** [comment]
Awesome. Thanks.
