### ISSUE TITLE
Flagging Subdomain Blog Content on Multisite

### ISSUE THREAD

**Issue by mrjarbenne** [francescolaffi/BP-Moderation#15]
When I attempt to flag content on a sub-domain blog in a multisite install, the content is flagged appropriately, and the moderation record appears in the Network Admin dashboard, but the "view" link, that should take me to the flagged content, takes me to the main domain/wp-admin page. 

Using BP 1.8.1
WPMS 3.6
BP-Mod 0.1.8-dev

**Comment by jo-greenwood** [comment]
Hi, I have a similar issue. 

I am running buddypress on a subdomain of a multisite install. I also have problems viewing flagged content from the dashboard. The 'view' link for 'activity comments' returns a 404 (the link resolves fine for 'status updates'). 

I am also unable to delete individual entries from the dashboard (this applies to both 'activity comments' and 'status updates'). If I delete via the 'delete' link or via 'bulk actions' the entry is marked as 'Status: moderated (deleted)' but it still remains visible.

BP 1.8.1
WPMS 3.6.1
BP Mod 0.1.7

**Comment by mrjarbenne** [comment]
This seems to be fixed in the latest update.
