### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by ghost** [francescolaffi/BP-Moderation#16]
Fatal error: func_get_args(): Can't be used as a function parameter in /Users/vichiho/Sites/rulebase.com/wp-content/plugins/bp-moderation/bpModLoader.php on line 118

**Comment by danibatoy** [comment]
Change the following lines...

function call_activate()
{
$this->call_installer('activate', func_get_args());
}

to

function call_activate()
{$fargs = func_get_args();
$this->call_installer('activate', $fargs );
}

and the same to disable..

**Comment by francescolaffi** [comment]
PHP 5.3 is required. There will be other incompatible code with php<5.3
