### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by ralstonandanthony** [francescolaffi/BP-Moderation#17]
Fatal error: func_get_args(): Can't be used as a function parameter in /home1/savteam5/public_html/wp-content/plugins/bp-moderation/bpModLoader.php on line 119

WordPress: 3.7.1
BuddyPress: 1.8.1
PHP: 5

**Comment by francescolaffi** [comment]
duplicate #16
