### ISSUE TITLE
WP 3.8 and BP 1.9 compatibility

### ISSUE THREAD

**Issue by francescolaffi** [francescolaffi/BP-Moderation#18]
test with new wp and bp version and patch any incompatible or deprecated stuff.
ETA: 20-something December

**Comment by discdemo** [comment]
Francesco, hello!

Just wanted to drop this comment for your awareness, although, u may already know about it. I have the latest WP and BP and see this in my site under members.

Also, I cannot deactivate, not delete to remove the error. Thanks for any feedback as you look into testing.

Fatal error: Call to undefined function bp_forums_get_topic_posts() in /home/massagem/public_html/wp-content/plugins/bp-moderation/classes/bpModDefaultContentTypes.php on line 603

-jz

**Comment by discdemo** [comment]
p.s. Renaming the folder cleared my issue, but I'll be interested to hear if this can be used with the latest. Thank you!
