### ISSUE TITLE
Flag/Unflag link is outside of <li>, kicked down to next line.

### ISSUE THREAD

**Issue by benjino** [francescolaffi/BP-Moderation#4]
In .activity-comments the Flag link is outside of the <li> and should be in the .acomments-options class, and so gets kicked down to the next line. See attached screenshot.
![activity_streams_directory](https://f.cloud.github.com/assets/3208630/717286/3421efa8-df49-11e2-9cc8-07309c170cf3.png)
![activity_streams_directory-2](https://f.cloud.github.com/assets/3208630/717287/3423673e-df49-11e2-8c34-674d71e8758e.png)

**Comment by francescolaffi** [comment]
thanks for the detailed explanation, probably a hook changed in the bp theme, should be an easy fix

for my own future reference, it should use the hook at: https://github.com/buddypress/BuddyPress/blob/1.7.2/bp-themes/bp-default/activity/comment.php#L50

**Comment by benjino** [comment]
Alright thanks, I'll wait for you to make the update. Any guess when that might be?

**Comment by francescolaffi** [comment]
Taking my last uni exam this week, should be able to fix the issues and
push an update on friday

-- Francesco Laffi
Sent from mobile

On 01/lug/2013, at 02:19, benjino notifications@github.com wrote:

Alright thanks, I'll wait for you to make the update. Any guess when that
might be?

—
Reply to this email directly or view it on
GitHubhttps://github.com/francescolaffi/BP-Moderation/issues/4#issuecomment-20258527
.

**Comment by benjino** [comment]
Wonderful, best wishes on your exam!
